# Generated by Django 5.2 on 2025-04-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemspedidos',
            old_name='total',
            new_name='total_item',
        ),
    ]
