# Generated by Django 5.2 on 2025-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_total_itemspedidos_total_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoarticulo',
            name='codigo_grupo',
            field=models.CharField(max_length=25),
        ),
    ]
