# Generated by Django 5.2 on 2025-05-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_grupoarticulo_codigo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaarticulo',
            name='codigo_linea',
            field=models.CharField(max_length=25),
        ),
    ]
