# Generated by Django 5.2 on 2025-05-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lineaarticulo_codigo_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='presentacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
