# Generated by Django 5.2 on 2025-05-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_articulo_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
