# Generated by Django 5.2 on 2025-05-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_articulo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo_barras',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
