# Generated by Django 5.2 on 2025-05-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_articulo_codigo_barras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='grupo_id',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='linea_id',
            new_name='linea',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='estado',
        ),
    ]
