"""
Django settings for pos_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*l)r)pkipnuz1%hntjq@@ik_wfmj$dpud!)^(gx!jc9f93jj!('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'accounts',
    # ...
    # 'django.contrib.sites',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.facebook',
    # ...

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
        # ... middleware existentes
    # 'django.contrib.sites.middleware.CurrentSiteMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',
]
# AUTHENTICATION_BACKENDS = [
#  # Needed to login by username in Django admin
#  'django.contrib.auth.backends.ModelBackend',
#  # `allauth` specific authentication methods
#  'allauth.account.auth_backends.AuthenticationBackend',
 
# ]

# SITE_ID = 1
# # Auth settings
# AUTH_USER_MODEL = 'accounts.Usuario' # Asegúrate de que está correctamente configurado
# LOGIN_REDIRECT_URL = 'home'
# LOGOUT_REDIRECT_URL = 'login'
# # Allauth settings
# ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = True
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
# ACCOUNT_EMAIL_VERIFICATION = 'optional'

# # Social providers settings
# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'APP': {
#             'client_id': 'tu-client-id-de-google',
#             'secret': 'tu-secret-de-google',
#             'key': ''
#         },
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         }
#     },
#     'facebook': {
#         'APP': {
#             'client_id': 'tu-client-id-de-facebook',
#             'secret': 'tu-secret-de-facebook',
#             'key': ''
#         },
#         'METHOD': 'oauth2',
#         'SCOPE': ['email', 'public_profile'],
#         'VERIFIED_EMAIL': True,
#     }
# }
ROOT_URLCONF = 'pos_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pos_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': 'dbpedidos',
    'USER': 'admin_pedidos',
    'PASSWORD': '1234567',
    'HOST': '127.0.0.1',
    'PORT': '5432'
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#Duracion de la sesion ( 2 semanas, en segundos)
SESSION_COOKIE_AGE = 1209600
# Cerrar la sesión cuando el usuario cierra el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# Usar cookies seguros (solo transmitir por HTTPS)
SESSION_COOKIE_SECURE = False # Cambiar a True en producción con HTTPS
# Motor de almacenamiento de sesiones
SESSION_ENGINE = 'django.contrib.sessions.backends.db' # Almacenar en la base de datos


# Configuración de Email 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
EMAIL_HOST = 'smtp.gmail.com'  # O tu proveedor SMTP 
EMAIL_PORT = 587 
EMAIL_USE_TLS = True 
EMAIL_HOST_USER = 'tu-email@gmail.com' 
EMAIL_HOST_PASSWORD = 'tu-contraseña-o-clave-de-app' 
DEFAULT_FROM_EMAIL = 'Sistema POS <tu-email@gmail.com>'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' 
